### ISSUE TITLE
Sadly the current version has stopped working

### ISSUE THREAD

**Issue by mrwrighty** [simplovation/WebMapsVE#1]
As off 8th September I had just found out that the current version has stopped working. Previous projects compiled and released into he wild are also failing and appears to be when setting the style of the maps.

Currently my code is failing at:-

`/* ----------------------------------------------------------------------------------- */
/* Copyright (C) Simplovation LLC (http://Simplovation.com) 2014. All rights reserved. */
/* Licensing information available at http://webmapsve.codeplex.com                    */
/* ----------------------------------------------------------------------------------- */
/*Map.js - Simplovation.Web.Maps.VE*/
Type.registerNamespace("Simplovation.Web.Maps.VE");
Simplovation.Web.Maps.VE.Map = function(element) {
    Simplovation.Web.Maps.VE.Map.initializeBase(this, [element]);

    this._Map = null; this._MainMapDiv = null;
    this._LatLong = null;
    this._Zoom = "4";
    this._MapStyle = "r";
    this._Fixed = false;
    this._MapMode = VEMapMode.Mode2D; <----- Here is where is crashes out first.
    this._ShowPoweredBy = true;
    this._ShowDashboard = true;
    this._Altitude = null;
    this._AltitudeSet = false;
    this._Pitch = null;
    this._Heading = null;
    this._ShowSwitch = true;
    this._DashboardSize = VEDashboardSize.Normal;
    this._TileBuffer = 0; this._Layers = null;
    this._ShowTraffic = false;
    this._ShowTrafficLegend = false;
    this._TrafficLegendText = null;
    this._AsyncPostbackPassShapes = true;
    this._AppPathRoot = null;
    this._AppPathDomain = null;
    this._CustomInfoBoxStylesEnabled = false;
    this._OnClientMapLoaded = null;
    this._FindArgs = null;
    this._ClientToken = null;
    this._BingKey = null;
    this._EnableBirdseye = true;
    this._EnableDashboardLabels = true;
    this._LoadBaseTiles = true;
    this._BirdseyeOrientation = null;

    this._ImportShapeLayerData_shapeSource = null;
    this._ImportShapeLayerData_setBestView = null;`

I have marked the line causing the issue.

**Comment by crpietschmann** [comment]
Unfortunately, the Web.Maps.VE control is written using the Microsoft Bing Maps v6.x JavaScript control that is no longer supported by Microsoft. When I moved the project to Github, I did start working on a port to use the newest Bing Maps v8 control, but I haven't had much time to dedicate to working on it. Feel free to check out the code and submit PR's. :)
